### ISSUE TITLE
Can't install bio-curve-fit

### ISSUE THREAD

**Issue by marseric** [Ganymede-Bio/bio-curve-fit#10]
Hello, I'm a beginner in Python and Linux. Glad I found this module, I tried to install your module on my computer (ubuntu16.04) but failed, can you take some time to take a look? thank U :)

test@ubuntu:~$ pip install bio-curve-fit
Collecting bio-curve-fit
  Using cached https://files.pythonhosted.org/packages/6c/f4/ac082466e590813c52082aa6a60a575a9bfaff3128851b2de73dd34e98bf/bio_curve_fit-0.1.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-qJnP9Y/bio-curve-fit/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qJnP9Y/bio-curve-fit/
You are using pip version 8.1.1, however version 23.3.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by bensonlee5** [comment]
Hi Marseric -

I think this may be failing due to an old version of python given the version of ubuntu.  To resolve, can you try creating a virtual environment using the following set of commonads:

> python -m venv .venv
> source .venv/bin/activate
> pip install --upgrade pip wheel setuptools
> pip install bio-curve-fit

**Comment by marseric** [comment]
Thank you. I update my computer to ubuntu 22.04.3. Now bio-curve-fit can be installed!
